export default function weapons_data() {
	return [
		{
			id: 5392,
			level: 5,
			required_level: 0,
			name: "Thistlewood Dagger",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 1161,
			level: 5,
			required_level: 0,
			name: "Militia Shortsword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 2137,
			level: 5,
			required_level: 0,
			name: "Whittling Knife",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 3267,
			level: 5,
			required_level: 0,
			name: "Forsaken Shortsword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 5579,
			level: 5,
			required_level: 0,
			name: "Militia Warhammer",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 5581,
			level: 5,
			required_level: 0,
			name: "Smooth Walking Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 3268,
			level: 5,
			required_level: 0,
			name: "Forsaken Dagger",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 5580,
			level: 5,
			required_level: 0,
			name: "Militia Hammer",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 5761,
			level: 5,
			required_level: 0,
			name: "Anvilmar Sledge",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 2048,
			level: 5,
			required_level: 0,
			name: "Anvilmar Hammer",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2224,
			level: 5,
			required_level: 0,
			name: "Militia Dagger",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 4924,
			level: 5,
			required_level: 0,
			name: "Primitive Club",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 5586,
			level: 5,
			required_level: 0,
			name: "Thistlewood Blade",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 5776,
			level: 5,
			required_level: 0,
			name: "Elder's Cane",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 1159,
			level: 5,
			required_level: 0,
			name: "Militia Quarterstaff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 2047,
			level: 5,
			required_level: 0,
			name: "Anvilmar Hand Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 2195,
			level: 5,
			required_level: 0,
			name: "Anvilmar Knife",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 3277,
			level: 5,
			required_level: 0,
			name: "Executor Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 5779,
			level: 5,
			required_level: 0,
			name: "Forsaken Bastard Sword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 10544,
			level: 5,
			required_level: 0,
			name: "Thistlewood Maul",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 1382,
			level: 5,
			required_level: 0,
			name: "Rock Mace",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 3269,
			level: 5,
			required_level: 0,
			name: "Forsaken Maul",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 4923,
			level: 5,
			required_level: 0,
			name: "Primitive Hatchet",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 4925,
			level: 5,
			required_level: 0,
			name: "Primitive Hand Blade",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 5778,
			level: 5,
			required_level: 0,
			name: "Primitive Walking Stick",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 1383,
			level: 5,
			required_level: 0,
			name: "Stone Tomahawk",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 5393,
			level: 5,
			required_level: 0,
			name: "Thistlewood Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 5777,
			level: 5,
			required_level: 0,
			name: "Brave's Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 3335,
			level: 6,
			required_level: 3,
			name: "Farmer's Broom",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 1195,
			level: 6,
			required_level: 3,
			name: "Kobold Mining Shovel",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 8177,
			level: 7,
			required_level: 2,
			name: "Practice Sword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 3334,
			level: 7,
			required_level: 2,
			name: "Farmer's Shovel",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 2492,
			level: 7,
			required_level: 2,
			name: "Cudgel",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "One-Hand",
		},
		{
			id: 766,
			level: 7,
			required_level: 2,
			name: "Flanged Mace",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2489,
			level: 7,
			required_level: 2,
			name: "Two-handed Sword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 778,
			level: 7,
			required_level: 2,
			name: "Kobold Excavation Pick",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 2138,
			level: 7,
			required_level: 2,
			name: "Sharpened Letter Opener",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 1412,
			level: 7,
			required_level: 2,
			name: "Crude Bastard Sword",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 1389,
			level: 7,
			required_level: 2,
			name: "Kobold Mining Mallet",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2491,
			level: 8,
			required_level: 3,
			name: "Large Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 2495,
			level: 8,
			required_level: 3,
			name: "Walking Stick",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 767,
			level: 8,
			required_level: 3,
			name: "Long Bo Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 2494,
			level: 8,
			required_level: 3,
			name: "Stiletto",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 3190,
			level: 8,
			required_level: 3,
			name: "Beatstick",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 3189,
			level: 8,
			required_level: 3,
			name: "Wood Chopper",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 1413,
			level: 8,
			required_level: 3,
			name: "Feeble Sword",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 10547,
			level: 8,
			required_level: 0,
			name: "Camping Knife",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 1411,
			level: 8,
			required_level: 3,
			name: "Withered Staff",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 1011,
			level: 8,
			required_level: 0,
			name: "Sharp Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 1010,
			level: 8,
			required_level: 0,
			name: "Gnarled Short Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 2066,
			level: 8,
			required_level: 3,
			name: "Skull Hatchet",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 2258,
			level: 8,
			required_level: 3,
			name: "Frostmane Shortsword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 2259,
			level: 8,
			required_level: 3,
			name: "Frostmane Club",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 1417,
			level: 8,
			required_level: 3,
			name: "Beaten Battle Axe",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 2488,
			level: 9,
			required_level: 4,
			name: "Gladius",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "One-Hand",
		},
		{
			id: 2493,
			level: 9,
			required_level: 4,
			name: "Wooden Mallet",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 768,
			level: 9,
			required_level: 4,
			name: "Lumberjack Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 2844,
			level: 9,
			required_level: 4,
			name: "Copper Mace",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 1414,
			level: 9,
			required_level: 4,
			name: "Cracked Sledge",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 4563,
			level: 9,
			required_level: 4,
			name: "Billy Club",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2845,
			level: 9,
			required_level: 4,
			name: "Copper Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 3225,
			level: 9,
			required_level: 4,
			name: "Bloodstained Knife",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 3319,
			level: 9,
			required_level: 4,
			name: "Short Sabre",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 781,
			level: 9,
			required_level: 4,
			name: "Stone Gnoll Hammer",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 1415,
			level: 9,
			required_level: 4,
			name: "Carpenter's Mallet",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2490,
			level: 9,
			required_level: 4,
			name: "Tomahawk",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "One-Hand",
		},
		{
			id: 2260,
			level: 9,
			required_level: 4,
			name: "Frostmane Hand Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 2065,
			level: 9,
			required_level: 4,
			name: "Rockjaw Blade",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 3325,
			level: 9,
			required_level: 4,
			name: "Vile Fin Battle Axe",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 3327,
			level: 9,
			required_level: 4,
			name: "Vile Fin Oracle Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 1416,
			level: 9,
			required_level: 4,
			name: "Rusty Hatchet",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 2847,
			level: 9,
			required_level: 4,
			name: "Copper Shortsword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 6365,
			level: 10,
			required_level: 5,
			name: "Strong Fishing Pole",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 20,
				name: "Fishing Pole",
			},
			type: "Two-Hand",
		},
		{
			id: 8178,
			level: 10,
			required_level: 5,
			name: "Training Sword",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 18957,
			level: 10,
			required_level: 0,
			name: "Brushwood Blade",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "One-Hand",
		},
		{
			id: 4562,
			level: 10,
			required_level: 5,
			name: "Severing Axe",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 2067,
			level: 10,
			required_level: 5,
			name: "Frostbit Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 9514,
			level: 10,
			required_level: 0,
			name: "Arcane Staff",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 727,
			level: 10,
			required_level: 5,
			name: "Notched Shortsword",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "One-Hand",
		},
		{
			id: 1917,
			level: 10,
			required_level: 5,
			name: "Jeweled Dagger",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 9513,
			level: 10,
			required_level: 0,
			name: "Ley Staff",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 5605,
			level: 10,
			required_level: 0,
			name: "Pruning Knife",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 1913,
			level: 10,
			required_level: 5,
			name: "Studded Blackjack",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 4302,
			level: 10,
			required_level: 5,
			name: "Small Green Dagger",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 2268,
			level: 10,
			required_level: 5,
			name: "Stonesplinter Blade",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 7094,
			level: 10,
			required_level: 5,
			name: "Driftwood Branch",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 1008,
			level: 10,
			required_level: 0,
			name: "Well-used Sword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 9603,
			level: 10,
			required_level: 0,
			name: "Gritroot Staff",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 2282,
			level: 10,
			required_level: 5,
			name: "Rodentia Shortsword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 3443,
			level: 10,
			required_level: 0,
			name: "Ceremonial Tomahawk",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 4840,
			level: 10,
			required_level: 0,
			name: "Long Bayonet",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 1158,
			level: 10,
			required_level: 0,
			name: "Solid Metal Club",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2257,
			level: 10,
			required_level: 5,
			name: "Frostmane Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 2056,
			level: 10,
			required_level: 5,
			name: "The Velvet Hammer",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 4961,
			level: 10,
			required_level: 0,
			name: "Dreamwatcher Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 2140,
			level: 11,
			required_level: 6,
			name: "Carving Knife",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 4938,
			level: 11,
			required_level: 0,
			name: "Blemished Wooden Staff",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 4948,
			level: 11,
			required_level: 0,
			name: "Stinging Mace",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2225,
			level: 11,
			required_level: 0,
			name: "Sharp Kitchen Knife",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 3455,
			level: 11,
			required_level: 0,
			name: "Deathstalker Shortsword",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "One-Hand",
		},
		{
			id: 816,
			level: 11,
			required_level: 6,
			name: "Small Hand Blade",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 7166,
			level: 11,
			required_level: 6,
			name: "Copper Dagger",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 2064,
			level: 11,
			required_level: 6,
			name: "Trogg Club",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 4939,
			level: 11,
			required_level: 0,
			name: "Steady Bastard Sword",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 7955,
			level: 11,
			required_level: 6,
			name: "Copper Claymore",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 3223,
			level: 11,
			required_level: 6,
			name: "Frostmane Scepter",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 4561,
			level: 11,
			required_level: 6,
			name: "Scalping Tomahawk",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 3329,
			level: 11,
			required_level: 6,
			name: "Spiked Wooden Plank",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 4932,
			level: 11,
			required_level: 0,
			name: "Harpy Wing Clipper",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 5595,
			level: 11,
			required_level: 0,
			name: "Thicket Hammer",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 2281,
			level: 11,
			required_level: 6,
			name: "Rodentia Flint Axe",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 4947,
			level: 11,
			required_level: 0,
			name: "Jagged Dagger",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 6651,
			level: 12,
			required_level: 7,
			name: "Broken Wine Bottle",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "One-Hand",
		},
		{
			id: 3103,
			level: 12,
			required_level: 0,
			name: "Coldridge Hammer",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 3192,
			level: 12,
			required_level: 7,
			name: "Short Bastard Sword",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 8,
				name: "Sword",
			},
			type: "Two-Hand",
		},
		{
			id: 2075,
			level: 12,
			required_level: 7,
			name: "Priest's Mace",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2254,
			level: 12,
			required_level: 7,
			name: "Icepane Warhammer",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 4974,
			level: 12,
			required_level: 0,
			name: "Compact Fighting Knife",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 5744,
			level: 12,
			required_level: 7,
			name: "Pale Skinner",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 1515,
			level: 12,
			required_level: 7,
			name: "Rough Wooden Staff",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 4964,
			level: 12,
			required_level: 0,
			name: "Goblin Smasher",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 4971,
			level: 12,
			required_level: 0,
			name: "Skorn's Hammer",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 4303,
			level: 12,
			required_level: 7,
			name: "Cranial Thumper",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 3445,
			level: 12,
			required_level: 0,
			name: "Ceremonial Knife",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 1510,
			level: 12,
			required_level: 7,
			name: "Heavy Hammer",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 3071,
			level: 12,
			required_level: 0,
			name: "Striking Hatchet",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 1512,
			level: 12,
			required_level: 7,
			name: "Crude Battle Axe",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 7298,
			level: 13,
			required_level: 0,
			name: "Blade of Cunning",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 3488,
			level: 13,
			required_level: 8,
			name: "Copper Battle Axe",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 4766,
			level: 13,
			required_level: 8,
			name: "Feral Blade",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 4566,
			level: 13,
			required_level: 8,
			name: "Sturdy Quarterstaff",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 6215,
			level: 13,
			required_level: 0,
			name: "Balanced Fighting Stick",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 3446,
			level: 13,
			required_level: 0,
			name: "Darkwood Staff",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 10,
				name: "Staff",
			},
			type: "Two-Hand",
		},
		{
			id: 1009,
			level: 13,
			required_level: 0,
			name: "Compact Hammer",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 3440,
			level: 13,
			required_level: 0,
			name: "Bonecracker",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 4564,
			level: 13,
			required_level: 8,
			name: "Spiked Club",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 1511,
			level: 13,
			required_level: 8,
			name: "Commoner's Sword",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 2218,
			level: 13,
			required_level: 0,
			name: "Craftsman's Dagger",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 2265,
			level: 13,
			required_level: 8,
			name: "Stonesplinter Axe",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 5459,
			level: 13,
			required_level: 0,
			name: "Defender Axe",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 5587,
			level: 13,
			required_level: 0,
			name: "Thornroot Club",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 2266,
			level: 13,
			required_level: 8,
			name: "Stonesplinter Dagger",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 4765,
			level: 14,
			required_level: 9,
			name: "Enamelled Broadsword",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 7,
				name: "Sword",
			},
			type: "Main Hand",
		},
		{
			id: 1196,
			level: 14,
			required_level: 9,
			name: "Tabar",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 1,
				name: "Axe",
			},
			type: "Two-Hand",
		},
		{
			id: 2632,
			level: 14,
			required_level: 9,
			name: "Curved Dagger",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 15,
				name: "Dagger",
			},
			type: "One-Hand",
		},
		{
			id: 852,
			level: 14,
			required_level: 9,
			name: "Mace",
			quality: "Common",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "One-Hand",
		},
		{
			id: 1514,
			level: 14,
			required_level: 9,
			name: "Rusty Warhammer",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 5,
				name: "Mace",
			},
			type: "Two-Hand",
		},
		{
			id: 4569,
			level: 14,
			required_level: 9,
			name: "Staunch Hammer",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 4,
				name: "Mace",
			},
			type: "Main Hand",
		},
		{
			id: 1516,
			level: 14,
			required_level: 9,
			name: "Worn Hatchet",
			quality: "Poor",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
		{
			id: 5344,
			level: 14,
			required_level: 0,
			name: "Pointed Axe",
			quality: "Uncommon",
			item_class: {
				id: 2,
				name: "Weapon",
			},
			item_subclass: {
				id: 0,
				name: "Axe",
			},
			type: "Main Hand",
		},
	];
}
